//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eat_Beat.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eat_Beat.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección:.
        /// </summary>
        internal static string labelAddress {
            get {
                return ResourceManager.GetString("labelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña:.
        /// </summary>
        internal static string labelConfPassword {
            get {
                return ResourceManager.GetString("labelConfPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODIFICAR MÚSICO.
        /// </summary>
        internal static string labelEditMusician {
            get {
                return ResourceManager.GetString("labelEditMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODIFICAR RESTAURANTE.
        /// </summary>
        internal static string labelEditRestaurant {
            get {
                return ResourceManager.GetString("labelEditRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        internal static string labelEmail {
            get {
                return ResourceManager.GetString("labelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud:.
        /// </summary>
        internal static string labelLatitut {
            get {
                return ResourceManager.GetString("labelLatitut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud:.
        /// </summary>
        internal static string labelLongitut {
            get {
                return ResourceManager.GetString("labelLongitut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Músicos.
        /// </summary>
        internal static string labelMusicians {
            get {
                return ResourceManager.GetString("labelMusicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string labelName {
            get {
                return ResourceManager.GetString("labelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUEVO MÚSICO.
        /// </summary>
        internal static string labelNewMusician {
            get {
                return ResourceManager.GetString("labelNewMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUEVO RESTAURANTE.
        /// </summary>
        internal static string labelNewRestaurant {
            get {
                return ResourceManager.GetString("labelNewRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número:.
        /// </summary>
        internal static string labelNum {
            get {
                return ResourceManager.GetString("labelNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num. Dirección.
        /// </summary>
        internal static string labelNumAddress {
            get {
                return ResourceManager.GetString("labelNumAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        internal static string labelPostalCode {
            get {
                return ResourceManager.GetString("labelPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurantes.
        /// </summary>
        internal static string labelRestaurants {
            get {
                return ResourceManager.GetString("labelRestaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string labelUser {
            get {
                return ResourceManager.GetString("labelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atras.
        /// </summary>
        internal static string roundedButtonBack {
            get {
                return ResourceManager.GetString("roundedButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string roundedButtonCancel {
            get {
                return ResourceManager.GetString("roundedButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        internal static string roundedButtonContinue {
            get {
                return ResourceManager.GetString("roundedButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string roundedButtonCreate {
            get {
                return ResourceManager.GetString("roundedButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string roundedButtonDelete {
            get {
                return ResourceManager.GetString("roundedButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string roundedButtonEdit {
            get {
                return ResourceManager.GetString("roundedButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string roundedButtonModify {
            get {
                return ResourceManager.GetString("roundedButtonModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir.
        /// </summary>
        internal static string roundedButtonOpen {
            get {
                return ResourceManager.GetString("roundedButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir Calendario.
        /// </summary>
        internal static string roundedButtonOpenCalendar {
            get {
                return ResourceManager.GetString("roundedButtonOpenCalendar", resourceCulture);
            }
        }
    }
}
